import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignOutButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { GiAutoRepair } from 'react-icons/gi'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider
    
    >
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
           <header className="bg-[#2f406b] z-20 w-full fixed top-0 border-b-2  border-blue-100 p-4 items-center-safe space-x-3 flex justify-end h-[5rem]" >
            <SignedOut >
            <div  className='border rounded-2xl px-4 text-blue-200 hover:bg-blue-950'> 
               <SignInButton forceRedirectUrl="home/" mode='modal' >

                <button>Login</button>
               
                </SignInButton>
                
                </div>
           <div className='border rounded-2xl px-4 text-blue-200 hover:bg-blue-950'>
               <SignUpButton forceRedirectUrl="home/" mode='modal'>

               <button>Register</button>

               </SignUpButton>
           </div>
            </SignedOut>
            <SignedIn>
              <div className='flex text-blue-200 border-[#7a93de] h-9 opacity-80 gap-2 border  rounded-2xl p-1 hover:bg-[#353766FF]'>
                <h1>profile</h1>
               <div className='text-blue-200 border rounded-[50%] overflow-hidden animate-blink border-blue-100 opacity-100'> <UserButton /></div>
              </div>

               <div className='flex text-blue-200 px-2 gap-2 border rounded-2xl p-1 hover:bg-[#353766FF]'>
                <SignOutButton/>
             </div>
            </SignedIn>
          <div className="fixed  origin-left m-5 left-2.5 border-2 rounded-[30%] p-2 text-3xl border-blue-100 text-blue-100 flex-row flex spacing-x-4"><GiAutoRepair className=" mr-1.5 text-3xl animate-button_hinge"/>  WWAP </div>
        </header>
          {children}
             <footer className="bg-blue-100 border-t-2 border-blue-400 text-blue-700 h-[5rem] flex justify-center items-center"><h1>All rights reserved © {new Date().getFullYear() == 2025 ? 2025: "2025 - "+ new Date().getFullYear()}</h1></footer>
        
        </body>
      </html>
    </ClerkProvider>
  )
}